# Generated by Django 3.0.5 on 2025-05-18 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_auto_20250514_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdischargedetails',
            old_name='OtherCharge',
            new_name='otherCharge',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctorId',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patientId',
        ),
        migrations.RemoveField(
            model_name='patientdischargedetails',
            name='patientId',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.Doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.Patient'),
        ),
        migrations.AddField(
            model_name='patientdischargedetails',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.Patient'),
        ),
    ]
